kind: pipeline
type: docker
name: blog

steps:
  - name: build
    image: node
    commands:
      - npm i
      - npm run build

  - name: clean
    image: appleboy/drone-ssh
    settings:
      host: 121.40.126.12
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 5m
      script:
        - rm -rf /app/service/blog

  - name: upload
    image: appleboy/drone-scp
    settings:
      host: 121.40.126.12
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 2m
      source:
        - /drone/src/.output
        - /drone/src/run.sh
      target:
        - /app/service/blog/.output
        - /app/service/blog/run.sh

  - name: run
    image: appleboy/drone-ssh
    settings:
      host: 121.40.126.12
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 5m
      script:
        - cd /app/service/blog
        - chmod +x run.sh
        - ./run.sh
