apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: default
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
  replicas: 1
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: MYAPP:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: blog
                  key: DATABASE_URL
            - name: EMAIL_PASS
              valueFrom:
                configMapKeyRef:
                  name: blog
                  key: EMAIL_PASS
            - name: PORT
              value:
                number: 7100
          ports:
            - containerPort: 7100
              name: blog

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: blog
  namespace: default
data:
  DATABASE_URL: postgresql://postgres:147wsvaio.,,@111.229.192.102:5432/newblog?schema=public
  EMAIL_PASS: ohgcvxsvrqswbjjh
