name: deployment

on:
  push:
    branches: ["prod"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - env:
          DATABASE_URL: ${{ secrets.database_url }}
        run: |
          npm install
          npm run build
          npx prisma migrate deploy

      - uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          docker_name: blog

        with:
          host: 121.40.126.12
          user: root
          pass: ${{ secrets.ssh_password }}
          connect_timeout: 10s
          first_ssh: |
            rm -rf /app/service/blog
          scp: |
            ./.output/* => /app/service/blog
          last_ssh: |
            docker rm -fv $docker_name
            docker run -d -v /app/service/blog:/app -e PORT=7100 --name $docker_name -p 7100:7100 node node /app/server/index.mjs
